### ISSUE TITLE
NoMethodErorr: Sunspot encounters same hit twice in #populate_hits

### ISSUE THREAD

**Issue by rthbound** [sunspot/sunspot#239]
I'm having a problem with the `populate_hits` method in `sunspot-1.3.2/lib/sunspot/search/abstract_search.rb`

It seems like this method is encountering the same hit twice within the `data_accessor.load_all(ids).each do |result|` block.

```
def populate_hits #:nodoc:
  id_hit_hash = Hash.new { |h, k| h[k] = {} }
  hits.each do |hit|
    id_hit_hash[hit.class_name][hit.primary_key] = hit
  end
  id_hit_hash.each_pair do |class_name, hits|
    ids = hits.map { |id, hit| hit.primary_key }
    data_accessor = data_accessor_for(Util.full_const_get(class_name))
    hits_for_class = id_hit_hash[class_name]
    data_accessor.load_all(ids).each do |result|
    STDOUT.puts(result.inspect)
    STDOUT.puts hits_for_class.inspect
    STDOUT.puts Adapters::InstanceAdapter.adapt(result).id.to_s
      hit = hits_for_class.delete(Adapters::InstanceAdapter.adapt(result).id.to_s)
      hit.result = result
    end
    hits_for_class.values.each { |hit| hit.result = nil }
  end
end
```

I've used STDOUT to verify this:

```
 => #<UseCase::Result:0x0000000212a910 @success=true, @data={:search=><Sunspot::Search:{:fq=>["type:Persistence\\:\\:ActiveRecord\\:\\:OtRestaurant"], :q=>"Birmingham", :fl=>"* score", :qf=>"city_textp state_textp", :defType=>"dismax", :mm=>1, :start=>0, :rows=>30, :facet=>"true", :"f.pretty_restaurant_names_s.facet.mincount"=>1, :"facet.field"=>["pretty_restaurant_names_s", "taxonomy_s"], :"f.taxonomy_s.facet.mincount"=>1}>}> 
1.9.2p320 :010 > res.data[:search].results

  Persistence::ActiveRecord::OtRestaurant Load (66.4ms)  SELECT "ot_restaurants".* FROM "ot_restaurants" WHERE "ot_restaurants"."restaurant_id" IN (3141, 4041, 5143, 6613, 6655, 6660, 7500, 13210, 14635, 17662, 20926, 21094, 25216, 30130, 34456, 34558, 39892, 39895, 42379, 47419, 52867, 55093, 57802, 73363, 74311)


#<Persistence::ActiveRecord::OtRestaurant restaurant_id: 3141, restaurant_name: "Shula's Steak House - Birmingham", metro_name: "Alabama", address: "1000 Riverchase Galleria", city: "Birmingham", state: "AL", postal_code: "35244", phone: "2054445750", primary_food_type: "Steak", url: "www.donshula.com/locations.php?l=1&restid=2", reserve_url: "shulasbirmingham", payment_options: "Visa, MasterCard, AMEX, Diners Club, Discover, Cart...", restaurant_description: "Rated \"One of the top 5 Steak Houses in America\", S...", metro_id: 45, country_id: "0", latitude: "33.379616", longitude: "-86.805838", region_id: 83, region_name: "Birmingham", neighborhood_id: 653, neighborhood_name: "Birmingham", min_price: 50, private_party: true, created_at: "2012-05-29 17:50:56", updated_at: "2012-05-29 17:50:56">
{"3141"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 3141>, "4041"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 4041>, "5143"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 5143>, "6613"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 6613>, "6655"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 6655>, "6660"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 6660>, "7500"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 7500>, "13210"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 13210>, "14635"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 14635>, "17662"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 17662>, "20926"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 20926>, "21094"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 21094>, "25216"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 25216>, "30130"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 30130>, "34456"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 34456>, "34558"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 34558>, "39892"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 39892>, "39895"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 39895>, "42379"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 42379>, "47419"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 47419>, "52867"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 52867>, "55093"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 55093>, "57802"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 57802>, "73363"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 73363>, "74311"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 74311>}
3141
```

...

```
#<Persistence::ActiveRecord::OtRestaurant restaurant_id: 74311, restaurant_name: "Bluefin - Birmingham", metro_name: "Alabama", address: "1025 20th Street South", city: "Birmingham", state: "AL", postal_code: "35205", phone: "2059331025", primary_food_type: "Sushi", url: "bluefinbirmingham.com", reserve_url: "970D7647", payment_options: "Visa, MasterCard, AMEX, Discover", restaurant_description: "On any given night, you\"ll likely find a celebratio...", metro_id: 45, country_id: "0", latitude: "33.501328", longitude: "-86.796766", region_id: 83, region_name: "Birmingham", neighborhood_id: 653, neighborhood_name: "Birmingham", min_price: 30, private_party: true, created_at: "2012-05-29 17:59:22", updated_at: "2012-05-29 17:59:22">
{"74311"=>#<Sunspot::Search::Hit:Persistence::ActiveRecord::OtRestaurant 74311>}
74311
#<Persistence::ActiveRecord::OtRestaurant restaurant_id: 3141, restaurant_name: "Shula's Steak House - Birmingham", metro_name: "Alabama", address: "1000 Riverchase Galleria", city: "Birmingham", state: "AL", postal_code: "35244", phone: "2054445750", primary_food_type: "Steak", url: "www.donshula.com/locations.php?l=1&restid=2", reserve_url: "shulasbirmingham", payment_options: "Visa, MasterCard, AMEX, Diners Club, Discover, Cart...", restaurant_description: "Rated \"One of the top 5 Steak Houses in America\", S...", metro_id: 45, country_id: "0", latitude: "33.379616", longitude: "-86.805838", region_id: 83, region_name: "Birmingham", neighborhood_id: 653, neighborhood_name: "Birmingham", min_price: 50, private_party: true, created_at: "2012-05-29 06:02:45", updated_at: "2012-05-29 06:02:45">
{}
3141
NoMethodError: undefined method `result=' for nil:NilClass
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/sunspot-1.3.2/lib/sunspot/search/abstract_search.rb:233:in `block (2 levels) in populate_hits'
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/sunspot-1.3.2/lib/sunspot/search/abstract_search.rb:228:in `each'
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/sunspot-1.3.2/lib/sunspot/search/abstract_search.rb:228:in `block in populate_hits'
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/sunspot-1.3.2/lib/sunspot/search/abstract_search.rb:224:in `each_pair'
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/sunspot-1.3.2/lib/sunspot/search/abstract_search.rb:224:in `populate_hits'
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/sunspot-1.3.2/lib/sunspot/search/hit.rb:90:in `result'
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/sunspot-1.3.2/lib/sunspot/search/abstract_search.rb:278:in `block in verified_hits'
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/sunspot-1.3.2/lib/sunspot/search/paginated_collection.rb:50:in `select'
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/sunspot-1.3.2/lib/sunspot/search/paginated_collection.rb:50:in `method_missing'
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/sunspot-1.3.2/lib/sunspot/search/abstract_search.rb:278:in `verified_hits'
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/sunspot-1.3.2/lib/sunspot/search/abstract_search.rb:59:in `results'
from (irb):10
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands/console.rb:47:in `start'
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands/console.rb:8:in `start'
from /home/deployer/apps/mrarlo.com/shared/bundle/ruby/1.9.1/gems/railties-3.2.3/lib/rails/commands.rb:41:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'1.9.2p320 :011 > exit
```

I've confirmed my suspicion by monkey patching `sunspot-1.3.2/lib/sunspot/search/abstract_search.rb` to call `ids.uniq` right before `data_accessor.load_all(ids).each do |result|`

Please advise.

**Comment by ethirajsrinivasan** [comment]
Please use the latest version of the gem and if the problem still exists feel free to raise an issue
