### ISSUE TITLE
Missing cast method for LatLon type

### ISSUE THREAD

**Issue by jhecking** [sunspot/sunspot#288]
I'm trying to store a set of coordinates in solr using Sunspot's latlon type and retrieve them from the search results. However since the LatLonType class doesn't have a cast method trying to access the location in the hit's stored values throws a NoMethodError exception:

```
NoMethodError: undefined method `cast' for #<Sunspot::Type::LatlonType:0x007f84fd55de88>
```

Any concerns with adding a cast method to this type, e.g. like this:

```
diff --git a/sunspot/lib/sunspot/type.rb b/sunspot/lib/sunspot/type.rb
index fc8915a..b8101c4 100644
--- a/sunspot/lib/sunspot/type.rb
+++ b/sunspot/lib/sunspot/type.rb
@@ -373,6 +373,11 @@ module Sunspot
       def to_indexed(value)
         "#{value.lat.to_f},#{value.lng.to_f}"
       end
+      
+      def cast(string) #:nodoc:
+        lat, lng = string.split(',')
+        Sunspot::Util::Coordinates.new(lat, lng)
+      end
     end

     class ClassType < AbstractType
```

From my model definition:

```
latlon :location, :stored => true do
  Sunspot::Util::Coordinates.new(lat, long)
end
```

Sample code that demonstrates the NoMethodError

```
s = Space.find_by_location('paris')
 => <Sunspot::Search:{:fq=>["type:Space", "active_bs:true"], :sort=>"search_ranking_i desc, score desc", :q=>"paris", :fl=>"* score", :qf=>"city_texts country_texts state_texts", :defType=>"dismax", :mm=>1, :start=>0, :rows=>15, :facet=>"true", :"f.room_type_ss.facet.mincount"=>0, :"facet.field"=>["room_type_ss", "{!key=amenities}aminities_sms", "{!ex= key=amenities_all}aminities_sms", "tags_sms"], :"f.amenities.facet.mincount"=>0, :"f.amenities_all.facet.mincount"=>0, :"f.tags_sms.facet.mincount"=>0}> 
h = s.hits
 => [#<Sunspot::Search::Hit:Space 95pVTNiYY5k>, #<Sunspot::Search::Hit:Space dxjM003wV9i>, #<Sunspot::Search::Hit:Space Y9bukkQNGvc>, #<Sunspot::Search::Hit:Space nB849zAjX9r>, #<Sunspot::Search::Hit:Space D4JTKOV1Nsk>, #<Sunspot::Search::Hit:Space lHJqKTCDr0e>] 
h1 = h.first
 => #<Sunspot::Search::Hit:Space 95pVTNiYY5k> 
h1.stored(:location)
NoMethodError: undefined method `cast' for #<Sunspot::Type::LatlonType:0x007f84fd55de88>
    from /Users/jhecking/.rvm/gems/ruby-1.9.3-p194/gems/sunspot-2.0.0.pre.120720/lib/sunspot/field.rb:58:in `cast'
    from /Users/jhecking/.rvm/gems/ruby-1.9.3-p194/gems/sunspot-2.0.0.pre.120720/lib/sunspot/search/hit.rb:142:in `block in stored_value'
    from /Users/jhecking/.rvm/gems/ruby-1.9.3-p194/gems/sunspot-2.0.0.pre.120720/lib/sunspot/search/hit.rb:136:in `each'
    from /Users/jhecking/.rvm/gems/ruby-1.9.3-p194/gems/sunspot-2.0.0.pre.120720/lib/sunspot/search/hit.rb:136:in `stored_value'
    from /Users/jhecking/.rvm/gems/ruby-1.9.3-p194/gems/sunspot-2.0.0.pre.120720/lib/sunspot/search/hit.rb:80:in `stored'
    from (irb):4
    from /Users/jhecking/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.0.8/lib/rails/commands/console.rb:44:in `start'
    from /Users/jhecking/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.0.8/lib/rails/commands/console.rb:8:in `start'
    from /Users/jhecking/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.0.8/lib/rails/commands.rb:23:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by ethirajsrinivasan** [comment]
@jhecking 

```ruby
s = Space.find_by_location('paris')
 => <Sunspot::Search:{:fq=>["type:Space", "active_bs:true"], :sort=>"search_ranking_i desc, score desc", :q=>"paris", :fl=>"* score", :qf=>"city_texts country_texts state_texts", :defType=>"dismax", :mm=>1, :start=>0, :rows=>15, :facet=>"true", :"f.room_type_ss.facet.mincount"=>0, :"facet.field"=>["room_type_ss", "{!key=amenities}aminities_sms", "{!ex= key=amenities_all}aminities_sms", "tags_sms"], :"f.amenities.facet.mincount"=>0, :"f.amenities_all.facet.mincount"=>0, :"f.tags_sms.facet.mincount"=>0}> 
```
Few questions
*Is find_by_location your customized method and are you using solr search inside this method?
*Can you share the db structure  for this model (fields relative to latlon is sufficent)?
*I am trying to reproduce the error so can you share more information or steps to generate this error in a detailed manner.

**Comment by jhecking** [comment]
Hi @ethirajsrinivasan, I'm no longer working on this code base and don't have access to it any more. From memory, yes, `find_by_location` sets up a Solr search, executes it and returns the results. I do not recall the exact db structure used for this model.
