### ISSUE TITLE
TypeError after bundle

### ISSUE THREAD

**Issue by Richenglish** [sunspot/sunspot#557]
After adding the gem and running bundle, I am unable to restart Rails.

```
/Users/rich/.rvm/gems/ruby-2.0.0-p247/gems/sunspot_rails-1.3.3/lib/sunspot/rails/configuration.rb:297:in `join': no implicit conversion of nil into String (TypeError)
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/sunspot_rails-1.3.3/lib/sunspot/rails/configuration.rb:297:in `user_configuration'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/sunspot_rails-1.3.3/lib/sunspot/rails/configuration.rb:281:in `user_configuration_from_key'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/sunspot_rails-1.3.3/lib/sunspot/rails/configuration.rb:256:in `disabled?'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/sunspot_rails-1.3.3/lib/sunspot/rails.rb:30:in `build_session'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/sunspot_rails-1.3.3/lib/sunspot/rails/init.rb:1:in `<top (required)>'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/sunspot_rails-1.3.3/lib/sunspot_rails.rb:11:in `<top (required)>'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `require'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:72:in `block (2 levels) in require'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `each'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:70:in `block in require'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `each'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler/runtime.rb:59:in `require'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247@global/gems/bundler-1.3.5/lib/bundler.rb:132:in `require'
    from /Users/richardenglish/Desktop/hoodboom/config/application.rb:7:in `<top (required)>'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands.rb:76:in `require'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands.rb:76:in `block in <top (required)>'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands.rb:73:in `tap'
    from /Users/richardenglish/.rvm/gems/ruby-2.0.0-p247/gems/railties-4.0.0/lib/rails/commands.rb:73:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by pamio** [comment]
Has anyone solved this issue yet ? Im also facing the same issue. 
I have two app with different rails versions. 
App 1 
   rails 3.2.13
   ruby 2.1.1

App2
   rails 4.2
   ruby 2.1.1

I dont have any issues in app1, I can see my indexed data but app2 doesnt work, meaning, it doesnt boot up. 

Im using `sunspot_rails-2.0.0.pre.120417`

**Comment by mlh758** [comment]
Closing this due to age.
