### ISSUE TITLE
solr server won't start with 2.1.0

### ISSUE THREAD

**Issue by jakewendt** [sunspot/sunspot#566]
I've been trying to upgrade my rails 4 app on my Mac from sunspot 2.0.0 to 2.1.0 to no avail.  With sunspot 2.0.0 everything works great, but I like to keep things current, particularly given the existence of a few rails deprecation warnings.  But with 2.1.0, the server just won't start.  I've tried java 1.6 and 1.7 both with the same results.  `bundle exec rake sunspot:solr:start` would always say it succeeded, but actually failed quietly and  `bundle exec rake sunspot:solr:run` would explicitly fail as shown below.

```
> java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)

> java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
```

I even went so far as to just create a new app and it still won't start.

```
> rails new sunspot_test --skip-bundle
> cd sunspot_test/
> vi Gemfile 

> cat Gemfile
source 'https://rubygems.org'


gem 'rails', '4.1.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development

gem 'sunspot_solr'
gem 'sunspot_rails'



> sudo gem uninstall sunspot sunspot_rails sunspot_solr

> sudo bundle up
Fetching gem metadata from https://rubygems.org/..........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using rake (10.3.0)
Using i18n (0.6.9)
Using json (1.8.1)
Using minitest (5.3.3)
Using thread_safe (0.3.3)
Using tzinfo (1.1.0)
Using activesupport (4.1.0)
Using builder (3.2.2)
Using erubis (2.7.0)
Using actionview (4.1.0)
Using rack (1.5.2)
Using rack-test (0.6.2)
Using actionpack (4.1.0)
Using mime-types (1.25.1)
Using polyglot (0.3.4)
Using treetop (1.4.15)
Using mail (2.5.4)
Using actionmailer (4.1.0)
Using activemodel (4.1.0)
Using arel (5.0.1.20140414130214)
Using activerecord (4.1.0)
Using bundler (1.5.3)
Using coffee-script-source (1.7.0)
Using execjs (2.0.2)
Using coffee-script (2.2.0)
Using thor (0.19.1)
Using railties (4.1.0)
Using coffee-rails (4.0.1)
Using hike (1.2.3)
Using multi_json (1.9.2)
Using jbuilder (2.0.6)
Using jquery-rails (3.1.0)
Using mini_portile (0.5.3)
Using nokogiri (1.6.1)
Using pr_geohash (1.0.0)
Using tilt (1.4.1)
Using sprockets (2.11.0)
Using sprockets-rails (2.1.3)
Using rails (4.1.0)
Using rdoc (4.1.1)
Using rsolr (1.0.10)
Using sass (3.2.19)
Using sass-rails (4.0.3)
Using sdoc (0.4.0)
Using spring (1.1.2)
Using sqlite3 (1.3.9)
Installing sunspot (2.1.0)
Installing sunspot_rails (2.1.0)
Installing sunspot_solr (2.1.0)
Using turbolinks (2.2.2)
Using uglifier (2.5.0)
Your bundle is updated!



> rails generate sunspot_rails:install
DEPRECATION WARNING: You have required `active_support/core_ext/object/to_json`. This file will be removed in Rails 4.2. You should require `active_support/core_ext/object/json` instead. (called from <top (required)> at /Users/jakewendt/sunspot_test/config/application.rb:7)
      create  config/sunspot.yml

> bundle exec rake sunspot:solr:run
DEPRECATION WARNING: You have required `active_support/core_ext/object/to_json`. This file will be removed in Rails 4.2. You should require `active_support/core_ext/object/json` instead. (called from <top (required)> at /Users/jakewendt/sunspot_test/config/application.rb:7)
Copying /opt/local/lib/ruby2.0/gems/2.0.0/gems/sunspot_solr-2.1.0/solr/solr/conf/admin-extra.html => /Users/jakewendt/sunspot_test/solr/conf/admin-extra.html
Copying /opt/local/lib/ruby2.0/gems/2.0.0/gems/sunspot_solr-2.1.0/solr/solr/conf/elevate.xml => /Users/jakewendt/sunspot_test/solr/conf/elevate.xml
Copying /opt/local/lib/ruby2.0/gems/2.0.0/gems/sunspot_solr-2.1.0/solr/solr/conf/mapping-ISOLatin1Accent.txt => /Users/jakewendt/sunspot_test/solr/conf/mapping-ISOLatin1Accent.txt
Copying /opt/local/lib/ruby2.0/gems/2.0.0/gems/sunspot_solr-2.1.0/solr/solr/conf/protwords.txt => /Users/jakewendt/sunspot_test/solr/conf/protwords.txt
Copying /opt/local/lib/ruby2.0/gems/2.0.0/gems/sunspot_solr-2.1.0/solr/solr/conf/schema.xml => /Users/jakewendt/sunspot_test/solr/conf/schema.xml
Copying /opt/local/lib/ruby2.0/gems/2.0.0/gems/sunspot_solr-2.1.0/solr/solr/conf/scripts.conf => /Users/jakewendt/sunspot_test/solr/conf/scripts.conf
Copying /opt/local/lib/ruby2.0/gems/2.0.0/gems/sunspot_solr-2.1.0/solr/solr/conf/solrconfig.xml => /Users/jakewendt/sunspot_test/solr/conf/solrconfig.xml
Copying /opt/local/lib/ruby2.0/gems/2.0.0/gems/sunspot_solr-2.1.0/solr/solr/conf/spellings.txt => /Users/jakewendt/sunspot_test/solr/conf/spellings.txt
Copying /opt/local/lib/ruby2.0/gems/2.0.0/gems/sunspot_solr-2.1.0/solr/solr/conf/stopwords.txt => /Users/jakewendt/sunspot_test/solr/conf/stopwords.txt
Copying /opt/local/lib/ruby2.0/gems/2.0.0/gems/sunspot_solr-2.1.0/solr/solr/conf/synonyms.txt => /Users/jakewendt/sunspot_test/solr/conf/synonyms.txt
Copying /opt/local/lib/ruby2.0/gems/2.0.0/gems/sunspot_solr-2.1.0/solr/solr/solr.xml => /Users/jakewendt/sunspot_test/solr
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.jetty.start.Main.invokeMain(Main.java:472)
	at org.eclipse.jetty.start.Main.start(Main.java:620)
	at org.eclipse.jetty.start.Main.main(Main.java:95)
Caused by: java.lang.NoSuchMethodError: org.slf4j.helpers.MessageFormatter.arrayFormat(Ljava/lang/String;[Ljava/lang/Object;)Lorg/slf4j/helpers/FormattingTuple;
	at org.eclipse.jetty.util.log.JettyAwareLogger.log(JettyAwareLogger.java:619)
	at org.eclipse.jetty.util.log.JettyAwareLogger.debug(JettyAwareLogger.java:206)
	at org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:89)
	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1203)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1189)
	... 7 more

Usage: java -jar start.jar [options] [properties] [configs]
       java -jar start.jar --help  # for more information

```

Does anyone have any suggestions?

**Comment by bragboy** [comment]
Please free to reopen this issue if its still a problem in the recent versions of sunspot
