### ISSUE TITLE
sunspot:reindex   NameError: uninitialized constant ApplicationController

### ISSUE THREAD

**Issue by clevertechru** [sunspot/sunspot#607]
```
rails 3.2
sunspot 2.1.1
```

```
RAILS_ENV=production bundle exec rake sunspot:solr:start            OK
```

but: 

```
RAILS_ENV=production bundle exec rake sunspot:reindex --trace
Net::NTLM is not available. Install via gem install rubyntlm.
** Invoke sunspot:reindex (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute sunspot:reindex
rake aborted!
NameError: uninitialized constant ApplicationController
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/declarative_authorization-0.5.7/app/controllers/authorization_rules_controller.rb:258:in `<top (required)>'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:359:in `require_or_load'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:313:in `depend_on'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:225:in `require_dependency'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-3.2.13/lib/rails/engine.rb:439:in `block (2 levels) in eager_load!'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-3.2.13/lib/rails/engine.rb:438:in `each'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-3.2.13/lib/rails/engine.rb:438:in `block in eager_load!'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-3.2.13/lib/rails/engine.rb:436:in `each'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-3.2.13/lib/rails/engine.rb:436:in `eager_load!'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-3.2.13/lib/rails/application/railties.rb:8:in `each'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-3.2.13/lib/rails/application/railties.rb:8:in `all'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-3.2.13/lib/rails/engine.rb:434:in `eager_load!'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sunspot_rails-2.1.1/lib/sunspot/rails/tasks.rb:33:in `block (3 levels) in <top (required)>'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sunspot_rails-2.1.1/lib/sunspot/rails/tasks.rb:68:in `with_session'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sunspot_rails-2.1.1/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
/Users/master/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
```

**Comment by mlh758** [comment]
Closing this due to age.
