### ISSUE TITLE
Sunspot.commit raises Net::ReadTimeout: Net::ReadTimeout

### ISSUE THREAD

**Issue by IslamAzab** [sunspot/sunspot#640]
Is there anyway to configure the timeout of Sunspot.commit only?

```
Net::ReadTimeout: Net::ReadTimeout
        from /usr/local/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill'
        from /usr/local/lib/ruby/2.0.0/net/protocol.rb:152:in `rbuf_fill'
        from /usr/local/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
        from /usr/local/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
        from /usr/local/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
        from /usr/local/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
        from /usr/local/lib/ruby/2.0.0/net/http.rb:1405:in `block in transport_request'
        from /usr/local/lib/ruby/2.0.0/net/http.rb:1402:in `catch'
        from /usr/local/lib/ruby/2.0.0/net/http.rb:1402:in `transport_request'
        from /usr/local/lib/ruby/2.0.0/net/http.rb:1375:in `request'
        from /usr/local/lib/ruby/gems/2.0.0/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
        from /usr/local/lib/ruby/gems/2.0.0/gems/newrelic_rpm-3.5.7.59/lib/new_relic/agent/instrumentation/net.rb:22:in `block in request_with_newrelic_trace'
        from /usr/local/lib/ruby/gems/2.0.0/gems/newrelic_rpm-3.5.7.59/lib/new_relic/agent/method_tracer.rb:240:in `trace_execution_scoped'
        from /usr/local/lib/ruby/gems/2.0.0/gems/newrelic_rpm-3.5.7.59/lib/new_relic/agent/instrumentation/net.rb:21:in `request_with_newrelic_trace'
        from /usr/local/lib/ruby/2.0.0/net/http.rb:1368:in `block in request'
        from /usr/local/lib/ruby/2.0.0/net/http.rb:851:in `start'
... 21 levels...
        from /usr/local/lib/ruby/gems/2.0.0/gems/newrelic_rpm-3.5.7.59/lib/new_relic/agent/method_tracer.rb:240:in `trace_execution_scoped'
        from /usr/local/lib/ruby/gems/2.0.0/gems/newrelic_rpm-3.5.7.59/lib/new_relic/agent/method_tracer.rb:486:in `index__with_trace_SolrClient_Sunspot_index'
        from (irb):8:in `block (3 levels) in irb_binding'
        from (irb):8:in `each'
        from (irb):8:in `block (2 levels) in irb_binding'
        from /usr/local/lib/ruby/gems/2.0.0/gems/sunspot-2.1.1/lib/sunspot/session.rb:226:in `batch'
        from /usr/local/lib/ruby/gems/2.0.0/gems/sunspot-2.1.1/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `batch'
        from /usr/local/lib/ruby/gems/2.0.0/gems/sunspot-2.1.1/lib/sunspot.rb:497:in `batch'
        from (irb):7:in `block in irb_binding'
        from /usr/local/lib/ruby/gems/2.0.0/gems/activerecord-3.2.18/lib/active_record/relation/batches.rb:72:in `find_in_batches'
        from (irb):2
        from /usr/local/lib/ruby/gems/2.0.0/gems/railties-3.2.18/lib/rails/commands/console.rb:47:in `start'
        from /usr/local/lib/ruby/gems/2.0.0/gems/railties-3.2.18/lib/rails/commands/console.rb:8:in `start'
        from /usr/local/lib/ruby/gems/2.0.0/gems/railties-3.2.18/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:6:in `require'
```

**Comment by phoenixwizard** [comment]
Any success with this?

**Comment by IslamAzab** [comment]
@phoenixwizard Not yet, I had to do it using http request to solr instead.

**Comment by benedictaluan** [comment]
Any success?

**Comment by IslamAzab** [comment]
@phoenixwizard @benedictaluan I had to add these options in `sunspot.yml` file

```
solr:
    hostname: localhost
    port: 1234
    log_level: WARN
    read_timeout: 20
    open_timeout: 10
  auto_commit_after_request: false
  auto_commit_after_delete_request: false
```

Although `Sunspot.commit` works fine, `Sunspot.optimize` sometimes gives timeout.

**Comment by danmayer** [comment]
by the way I ran into this issue and found this while googling... I was hitting the timeout every time I called `optimize`

I resolved by having the timeout set very high for optimize which is called in a single cron job. If one wanted to be more careful you could grab existing read_timeout, temporarily make it larger, fork it off to execute it and then reset the timeout... but the extremely simple version worked for me as cron tasks are single processes in my setup.

```
    def self.slow_optimize
      Sunspot.config.solr.read_timeout = 800;
      Sunspot.optimize()
    end
```

**Comment by mwlang** [comment]
Is it possible to configure Sunspot.commit to wait indefinitely?  i.e. nil or 0 to indicate wait forever.

**Comment by mlh758** [comment]
The timeouts should be in seconds. Closing this since there appears to be answers to the original question.
