### ISSUE TITLE
Matching substrings in fulltext search issue with rails 4.2.1

### ISSUE THREAD

**Issue by manish-shrivastava** [sunspot/sunspot#700]
### Environment Setup:
- Ruby 2.2.2
- Rails 4.2.1
- Sunspot
  -  sunspot (2.2.0)
  -  sunspot_rails (2.2.0)
  -  sunspot_solr (2.2.0)
### Description:

I follow instructionset from [Matching substrings in fulltext search guide](https://github.com/sunspot/sunspot/wiki/Matching-substrings-in-fulltext-search). and  after setting above setups, when I tried to run `rake sunspot:solr:reindex`, I get error as below:

```
user@user-Latitude-E5440:~/Desktop/projects/learn/sunspottest$ rake sunspot:solr:reindex --trace
** Invoke sunspot:solr:reindex (first_time)
** Invoke sunspot:reindex (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute sunspot:reindex
Skipping progress bar: for progress reporting, add gem 'progress_bar' to your Gemfile
rake aborted!
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {'responseHeader'=>{'status'=>400,'QTime'=>0},'error'=>{'msg'=>'ERROR: [doc=HighScore 1] unknown field \'game_textp\'','code'=>400}}

URI: http://localhost:8982/solr/development/update?wt=ruby
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"id\">HighScore 1</field><field name=\"type\">HighScore</field><field name=\"type\">ActiveRecord::Base</field><field name=\"class_name\">HighScore</field><field name=\"game_textp\">Cricket</field><field name=\"score_text\">100</field></doc><doc><field name=\"id\">HighScore 2</field><field name=\"type\">HighScore</field><field name=\"type\">ActiveRecord::Base</field><field name=\"class_name\">HighScore</field><field name=\"game_textp\">Soccer</field><field name=\"score_text\">1212</field></doc><doc><field name=\"id\">HighScore 3</field><field name=\"type\">HighScore</field><field name=\"type\">ActiveRecord::Base</field><field name=\"class_name\">HighScore</field><field name=\"game_textp\">Chess</field><field name=\"score_text\">12</field></doc></add>"

Backtrace: /home/user/.rvm/gems/ruby-2.2.2@sport/gems/rsolr-1.0.12/lib/rsolr/client.rb:284:in `adapt_response'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/rsolr-1.0.12/lib/rsolr/client.rb:190:in `execute'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/rsolr-1.0.12/lib/rsolr/client.rb:176:in `send_and_receive'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/rsolr-1.0.12/lib/rsolr/client.rb:82:in `update'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/rsolr-1.0.12/lib/rsolr/client.rb:102:in `add'/home/user/.rvm/gems/ruby-2.2.2@sport/gems/rsolr-1.0.12/lib/rsolr/client.rb:284:in `adapt_response'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/rsolr-1.0.12/lib/rsolr/client.rb:190:in `execute'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/rsolr-1.0.12/lib/rsolr/client.rb:176:in `send_and_receive'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/rsolr-1.0.12/lib/rsolr/client.rb:82:in `update'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/rsolr-1.0.12/lib/rsolr/client.rb:102:in `add'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot-2.2.0/lib/sunspot/indexer.rb:106:in `add_documents'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot-2.2.0/lib/sunspot/indexer.rb:29:in `add'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot-2.2.0/lib/sunspot/session.rb:91:in `index'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot-2.2.0/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `index'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot-2.2.0/lib/sunspot/session_proxy/retry_5xx_session_proxy.rb:17:in `method_missing'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot-2.2.0/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `index'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot-2.2.0/lib/sunspot.rb:184:in `index'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/searchable.rb:262:in `block (2 levels) in solr_index'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/searchable.rb:365:in `solr_benchmark'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/searchable.rb:261:in `block in solr_index'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/activerecord-4.2.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/searchable.rb:259:in `solr_index'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/searchable.rb:208:in `solr_reindex'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:58:in `block (4 levels) in <top (required)>'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot-2.2.0/lib/sunspot/class_set.rb:16:in `each'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot-2.2.0/lib/sunspot/class_set.rb:16:in `each'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:57:in `block (3 levels) in <top (required)>'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:69:in `with_session'
/home/user/.rvm/gems/ruby-2.2.2@sport/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/user/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/home/user/.rvm/rubies/ruby-2.2.2/bin/rake:33:in `<main>'
Tasks: TOP => sunspot:solr:reindex => sunspot:reindex

```

**Comment by IslamAzab** [comment]
What do you get when you `curl http://localhost:8982/solr/development` ?

**Comment by manish-shrivastava** [comment]
@IslamAzab I get output as below:

```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/development. Reason:
<pre>    Not Found</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                                          
<br/>                                                

</body>
</html>
```

**Comment by IslamAzab** [comment]
Try opening `http://localhost:8982/` and check cores available.

**Comment by mlh758** [comment]
Closing this due to age.
