### ISSUE TITLE
RSolr error when passing very high pagination parameter

### ISSUE THREAD

**Issue by neumanrq** [sunspot/sunspot#702]
We are using `sunspot_rails` (v.2.2.0). When inserting an _extreme_ high pagination parameters, e.g. 

``` Ruby
…
sunspot.paginate(page: 1000000000, per_page: 20)
…
```

an error of the following type is raised:

```

RSolr::Error::Http - 500 Internal Server Error Error: {'responseHeader'=>{'status'=>500,'QTime'=>10},'error'=>{'msg'=>'For input string: "2462462462440"','trace'=>'java.lang.NumberFormatException: For input string: "2462462462440" at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) at java.lang.Integer.parseInt(Integer.java:583) at java.lang.Integer.parseInt(Integer.java:615) at org.apache.solr.search.QParser.getSort(QParser.java:276) at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:123) at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:187) at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135) at org.apache.solr.core.SolrCore.execute(SolrCore.java:1797) at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:637) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:343)
```

I have a question associated to this behavior: Currently we rescue this "externally", but should this be rescued by sunspot internally, e.g. by sanitizing the fetched `page` parameter in
[sunspot/dsl/paginatable.rb](https://github.com/sunspot/sunspot/blob/master/sunspot/lib/sunspot/dsl/paginatable.rb)?

By experiment I found out that the highest possible non-breaking `page` parameter was `107374182`.

Best wishes,
Robin

**Comment by ethirajsrinivasan** [comment]
@neumanrq No this will not be rescued by sunspot internally.
