### ISSUE TITLE
Getting ActiveSupport::Concern::MultipleIncludedBlocks error in Sunspot 2.2.0

### ISSUE THREAD

**Issue by stephenhmarsh** [sunspot/sunspot#708]
Hi,

When I try to `bundle exec rake sunspot:reindex` in sunspot_rails 2.2.0, I run into the following:

```
rake aborted!
ActiveSupport::Concern::MultipleIncludedBlocks: Cannot define multiple 'included' blocks for a Concern
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/concern.rb:126:in `included'
dev/spree/core/app/models/spree/order/checkout.rb:6:in `<module:Checkout>'
dev/spree/core/app/models/spree/order/checkout.rb:3:in `<class:Order>'
dev/spree/core/app/models/spree/order/checkout.rb:2:in `<module:Spree>'
dev/spree/core/app/models/spree/order/checkout.rb:1:in `<top (required)>'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:457:in `load'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:457:in `block in load_file'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:647:in `new_constants_in'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:456:in `load_file'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:354:in `require_or_load'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:317:in `depend_on'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:233:in `require_dependency'
.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:471:in `each'
.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:471:in `block in eager_load!'
.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:469:in `each'
.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:469:in `eager_load!'
.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:34:in `block (4 levels) in <top (required)>'
.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:34:in `each'
.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:34:in `block (3 levels) in <top (required)>'
.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:69:in `with_session'
.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `call'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `each'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `each'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
.rvm/rubies/ruby-2.2.2/bin/rake:33:in `<main>'
Tasks: TOP => sunspot:reindex

```

When I run the same task with sunspot_rails 2.1.1, it works fine.  

I'm not sure it's a sunspot_rails bug... but doing some research it seems to maybe be related to loading models multiple times?  I noticed there were some changes here: https://github.com/sunspot/sunspot/commit/ec64df6a526d738f9f77c039679b344f908d3298   Should I be reconfiguring  my app in any way for that not to throw an error?

Any help would be greatly appreciated. Thanks

**Comment by ethirajsrinivasan** [comment]
Please use the latest version of Sunspot.If the issue persists provide more information on it.

**Comment by stephenhmarsh** [comment]
Thanks @ethirajsrinivasan -- apologies for not following up: the error was ultimately caused by code from another gem that implemented ActiveSupport::Concern poorly.
