### ISSUE TITLE
Getting "ActiveSupport::Concern::MultipleIncludedBlocks: Cannot define multiple 'included' blocks for a Concern" in 2.2.0

### ISSUE THREAD

**Issue by stephenhmarsh** [sunspot/sunspot#714]
Apologies for the question-y nature of this ticket, but my post(s) in the google group are stuck waiting for someone to approve them.

After two recent gem updates (Spree 2.4 to 3.0 and Sunspot 2.1.x to 2.2.x), the rake task `sunspot:reindex` blows up with
 `ActiveSupport::Concern::MultipleIncludedBlocks: Cannot define multiple 'included' blocks for a Concern`

Which comes from here: https://github.com/sunspot/sunspot/blob/master/sunspot_rails/lib/sunspot/rails/tasks.rb#L34

And is tripping up on here:
https://github.com/spree/spree/pull/6523/files

Full trace:

```
ActiveSupport::Concern::MultipleIncludedBlocks: Cannot define multiple 'included' blocks for a Concern
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/concern.rb:126:in `included'
dev/spree/core/app/models/spree/order/checkout.rb:6:in `<module:Checkout>'
dev/spree/core/app/models/spree/order/checkout.rb:3:in `<class:Order>'
dev/spree/core/app/models/spree/order/checkout.rb:2:in `<module:Spree>'
dev/spree/core/app/models/spree/order/checkout.rb:1:in `<top (required)>'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:457:in `load'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:457:in `block in load_file'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:647:in `new_constants_in'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:456:in `load_file'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:354:in `require_or_load'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:317:in `depend_on'
.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:233:in `require_dependency'
.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:471:in `each'
.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:471:in `block in eager_load!'
.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:469:in `each'
.rvm/gems/ruby-2.2.2/gems/railties-4.2.3/lib/rails/engine.rb:469:in `eager_load!'
.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:34:in `block (4 levels) in <top (required)>'
.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:34:in `each'
.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:34:in `block (3 levels) in <top (required)>'
.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:69:in `with_session'
.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.0/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `call'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `each'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `each'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rake/application.rb:75:in `run'
.rvm/rubies/ruby-2.2.2/bin/rake:33:in `<main>'
Tasks: TOP => sunspot:reindex
```

Sorry, I wish I understood the problem better, but possibly related to how Rails is autoloading??

Since I cannot rollback the Spree gem in my app, I have had to lock Sunspot to 2.1.1, (the rake task still works on that version).

Is there anything I can trouble-shoot, configuration-wise?? 

I read somewhere this can happen when a module is loaded more than once by Rails?? Could re-opening a class to monkey-patch it possibly trigger this??  
Any help would be greatly appreciated!

**Comment by mcfiredrill** [comment]
Had the same problem in my app.
Basically it boiled down to some files were being required twice in certain environments, therefore it was trying to define the included blocks in the concern twice and blowing up.

The solution was to follow namespace/directory naming convention so rails would load the files automatically instead of requiring them manually.

I have no idea if that is the same issue you are having, its a bit difficult to tell just glancing at that spree file. Maybe search for any places you are requiring files?

**Comment by bragboy** [comment]
Did you try with the new version `2.2.2` ?

**Comment by bikeath1337** [comment]
@mcfiredrill and @stephenhmarsh , was this resolved with 2.2.2?

**Comment by mcfiredrill** [comment]
For me, the problem was with my app, not the gem , so...

**Comment by bikeath1337** [comment]
Thanks!
