### ISSUE TITLE
Multiple range filter is not working with float or integer columns of joins

### ISSUE THREAD

**Issue by ashishprajapati** [sunspot/sunspot#770]
Basically, I wants to filter the all the data based on the respected range of prices those are present in Pricing model and searching data from Product model. Below you can find out the proper relationship and scope.

I have followed that https://github.com/sunspot/sunspot/wiki/Scoping-by-attribute-fields#disjunctions-and-conjunctions

**I am getting this error in short **

D, [2016-02-29T13:41:36.847079 #8793] DEBUG -- :   SOLR Request (5.4ms)  [ path=select parameters={fq: ["type:Product", "({!join from=product_id_i to=id_i}mrp_per_unit_f:[1.0 TO 100.0] OR {!join from=product_id_i to=id_i}mrp_per_unit_f:[101.0 TO 1000.0])"], start: 0, rows: 30, q: "*:*"} ]
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {'responseHeader'=>{'status'=>400,'QTime'=>1},'error'=>{'msg'=>'org.apache.solr.search.SyntaxError: Cannot parse \'mrp_per_unit_f:[1\\.0\': Encountered "<EOF>" at line 1, column 20.
Was expecting one of:
    "TO" ...
    <RANGE_QUOTED> ...
    <RANGE_GOOP> ...
    ','code'=>400}}

**This is my code that I am using in controller to perform the search**

```
@search = Product.search do 
	any_of do 
		with(:mrp_per_unit, 1..100) 
		with(:mrp_per_unit, 101..1000) 
	end 
end

```

**This is product modal. It is the main model from there I wants to search.**

```
class Product < ActiveRecord::Base
searchable do
    integer :id
    join(:mrp_per_unit, :target => Pricing, :type => :float, :join => { :from => :product_id, :to => :id })
  end
end

```

**This is Pricing model that contains the respected price of the product in mrp_per_unit column and that is of float type**

```
class Pricing < ActiveRecord::Base
  belongs_to :product
  searchable do
    integer :product_id
    float :mrp_per_unit
  end
end
```

**I have tried that in my terminal and it is causing that error. I am getting only in case of with the columns those are joined with the Product model. mrp_per_unit is joined with the product model by join mapping and it is of float type.**

```
2.2.2 :266 > @search = Product.search do any_of do with(:mrp_per_unit, 1..100); with(:mrp_per_unit, 101..1000) end end

D, [2016-02-29T13:41:36.847079 #8793] DEBUG -- :   SOLR Request (5.4ms)  [ path=select parameters={fq: ["type:Product", "({!join from=product_id_i to=id_i}mrp_per_unit_f:[1.0 TO 100.0] OR {!join from=product_id_i to=id_i}mrp_per_unit_f:[101.0 TO 1000.0])"], start: 0, rows: 30, q: "*:*"} ]
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {'responseHeader'=>{'status'=>400,'QTime'=>1},'error'=>{'msg'=>'org.apache.solr.search.SyntaxError: Cannot parse \'mrp_per_unit_f:[1\\.0\': Encountered "<EOF>" at line 1, column 20.
Was expecting one of:
    "TO" ...
    <RANGE_QUOTED> ...
    <RANGE_GOOP> ...
    ','code'=>400}}

URI: http://localhost:8982/solr/development/select?wt=ruby
Request Headers: {"Content-Type"=>"application/x-www-form-urlencoded; charset=UTF-8"}
Request Data: "fq=type%3AProduct&fq=%28%7B%21join+from%3Dproduct_id_i+to%3Did_i%7Dmrp_per_unit_f%3A%5B1%5C.0+TO+100%5C.0%5D+OR+%7B%21join+from%3Dproduct_id_i+to%3Did_i%7Dmrp_per_unit_f%3A%5B101%5C.0+TO+1000%5C.0%5D%29&start=0&rows=30&q=*%3A*"

Backtrace: /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response'
/home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute'
/home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive'
/home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.4/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
/home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
/home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
/home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.4/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/sunspot-2.2.4/lib/sunspot/search/abstract_search.rb:49:in `execute'
/home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.4/lib/sunspot/rails/searchable.rb:389:in `solr_execute_search'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/rsolr-1.0.13/lib/rsolr/client.rb:284:in `adapt_response'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/rsolr-1.0.13/lib/rsolr/client.rb:190:in `execute'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/rsolr-1.0.13/lib/rsolr/client.rb:176:in `send_and_receive'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.4/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.4/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
	from (eval):2:in `post'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/sunspot-2.2.4/lib/sunspot/search/abstract_search.rb:49:in `execute'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.4/lib/sunspot/rails/searchable.rb:389:in `solr_execute_search'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/sunspot_rails-2.2.4/lib/sunspot/rails/searchable.rb:165:in `solr_search'
	from (irb):266
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/yuvasoft/Desktop/Private/meridukan/bin/rails:8:in `<top (required)>'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/yuvasoft/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /home/yuvasoft/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/yuvasoft/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.2 :267 > 
```

Thanks in advance

**Comment by ashishprajapati** [comment]
I have solved that my self by doing some change. At least it is working for one column of pricings for me but still it will create problem when I wants to use more than one column of pricings table 

I have removed that query  and chaned to the 2nd one 
**1st query **
```
  join(:mrp_per_unit, :target => Pricing, :type => :float, :join => { :from => :product_id, :to => :id })
```

Changed the above query to below mentioned

**2nd query**
```
 float :pricing do
      pricing.mrp_per_unit
  end

```

thanks
