### ISSUE TITLE
RSolr::Error::ConnectionRefused: Connection refused 

### ISSUE THREAD

**Issue by abhinav098** [sunspot/sunspot#900]
i am trying to run rake sunspot:reindex 
and getting this error

rake aborted!
RSolr::Error::ConnectionRefused: Connection refused - {:data=>"{\"delete\":{\"query\":\"type:Post\"}}", :headers=>{"Content-Type"=>"application/json"}, :method=>:post, :params=>{:wt=>:json}, :query=>"wt=json", :path=>"update", :uri=>#<URI::HTTP http://localhost:8982/solr/development/update?wt=json>}
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:194:in `rescue in execute'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:186:in `execute'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:181:in `send_and_receive'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:84:in `update'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:147:in `delete_by_query'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/indexer.rb:68:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session.rb:197:in `block in remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session.rb:197:in `each'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session.rb:197:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session_proxy/retry_5xx_session_proxy.rb:17:in `method_missing'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot.rb:502:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/searchable.rb:190:in `solr_remove_all_from_index'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/searchable.rb:209:in `solr_reindex'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:60:in `block (4 levels) in <top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/class_set.rb:16:in `each'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/class_set.rb:16:in `each'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:59:in `block (3 levels) in <top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:71:in `with_session'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Faraday::ConnectionFailed: Failed to open TCP connection to localhost:8982 (Connection refused - connect(2) for "localhost" port 8982)
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:33:in `call'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/connection.rb:175:in `post'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:187:in `execute'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:181:in `send_and_receive'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:84:in `update'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:147:in `delete_by_query'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/indexer.rb:68:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session.rb:197:in `block in remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session.rb:197:in `each'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session.rb:197:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session_proxy/retry_5xx_session_proxy.rb:17:in `method_missing'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot.rb:502:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/searchable.rb:190:in `solr_remove_all_from_index'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/searchable.rb:209:in `solr_reindex'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:60:in `block (4 levels) in <top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/class_set.rb:16:in `each'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/class_set.rb:16:in `each'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:59:in `block (3 levels) in <top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:71:in `with_session'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Errno::ECONNREFUSED: Failed to open TCP connection to localhost:8982 (Connection refused - connect(2) for "localhost" port 8982)
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:33:in `call'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/connection.rb:175:in `post'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:187:in `execute'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:181:in `send_and_receive'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:84:in `update'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:147:in `delete_by_query'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/indexer.rb:68:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session.rb:197:in `block in remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session.rb:197:in `each'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session.rb:197:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session_proxy/retry_5xx_session_proxy.rb:17:in `method_missing'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot.rb:502:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/searchable.rb:190:in `solr_remove_all_from_index'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/searchable.rb:209:in `solr_reindex'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:60:in `block (4 levels) in <top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/class_set.rb:16:in `each'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/class_set.rb:16:in `each'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:59:in `block (3 levels) in <top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:71:in `with_session'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'

Caused by:
Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 8982
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:38:in `block in call'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/adapter/net_http.rb:33:in `call'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/response.rb:8:in `call'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/faraday-0.14.0/lib/faraday/connection.rb:175:in `post'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:187:in `execute'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:181:in `send_and_receive'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:84:in `update'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rsolr-2.1.0/lib/rsolr/client.rb:147:in `delete_by_query'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/indexer.rb:68:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session.rb:197:in `block in remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session.rb:197:in `each'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session.rb:197:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session_proxy/retry_5xx_session_proxy.rb:17:in `method_missing'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot.rb:502:in `remove_all'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/searchable.rb:190:in `solr_remove_all_from_index'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/searchable.rb:209:in `solr_reindex'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:60:in `block (4 levels) in <top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/class_set.rb:16:in `each'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot-2.2.8/lib/sunspot/class_set.rb:16:in `each'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:59:in `block (3 levels) in <top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:71:in `with_session'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/sunspot_rails-2.2.8/lib/sunspot/rails/tasks.rb:19:in `block (2 levels) in <top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/Users/kiprosh/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => sunspot:reindex
(See full trace by running task with --trace)

**Comment by titame** [comment]
Hello @abhinav098 , 

Just to confirm - before running `rake sunspot:reindex`, have you already started your Solr server with this command? - `rake sunspot:solr:start`

**Comment by abhinav098** [comment]
yes i have started it.. but theres some problem in starting the solr server as i can start it as many times as i want.. it doesnt give me the error of already running

**Comment by serggl** [comment]
make sure you run it on a correct port.
Also have you tried to open Solr manager in browser before submitting this issue?

**Comment by abhinav098** [comment]
i tried solr manager in browser on localhost:8982/solr 
but its not working.
How to run it on the correct port ?

**Comment by serggl** [comment]
all possible options described here https://github.com/sunspot/sunspot/tree/master/sunspot_solr
