### ISSUE TITLE
Cannot reindex solr container

### ISSUE THREAD

**Issue by jabawack81** [sunspot/sunspot#916]
I'm trying to add a solr container to my app but I once added I cannot find a way to reindex it everytime I try I get a 400 error:

  ```
SOLR Request (24.6ms)  [ path=update parameters={} ]
rake aborted!
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {
  "responseHeader":{
    "status":400,
    "QTime":5},
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"undefined field type",
    "code":400}}

URI: http://solr:8983/solr/development/update?wt=json
Request Headers: {"Content-Type"=>"text/xml"}
Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><delete><query>type:Page</query></delete>"
```

I'm trying to search in the page model this is my configuration:

```
  searchable do
    text    :title, default_boost: 2
    text    :body
    text    :properties, stored: true do
      properties.map(&:body)
    end
    integer :category_id
    string  :page_type, stored: true do
      page_type.name
    end
    string  :status_cd
    boolean :searchable
  end
```
and this is my docker-compose file:
```
version: '3.6'
services:
  app:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - "3000:3000"
    depends_on:
      - db
      - solr
    environment:
      DATABASE_URL: postgres://postgres@db
    networks:
      - default
  db:
    image: postgres:10.3-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  solr:
    image: solr:7.4.0-alpine
    ports:
      - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - development
    links:
      - db:db
volumes:
  solr: {}
  pgdata: {}
```
it could be the version of solr?

**Comment by serggl** [comment]
From the first overview seem like some Solr config files were not mounted

**Comment by jabawack81** [comment]
thank you, do you mean thee solr folder in the root of my rails project? I tried to mount them with:

```
    volumes:
      - ./solr:/opt/solr/server/solr/mycores
```
where ./solr is the folder generated when I started solr for the first time with
```
rake sunspot:solr:start
```

but if I do that the container explodes with this error:

```
solr_1  | 2018-09-21 15:40:39.639 ERROR (coreContainerWorkExecutor-2-thread-1) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be loaded on startup
solr_1  | org.apache.solr.common.SolrException: Unable to create core [development]
solr_1  | 	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1156) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:681) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197) ~[metrics-core-3.2.6.jar:3.2.6]
solr_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
solr_1  | 	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:209) ~[solr-solrj-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:14]
solr_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
solr_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
solr_1  | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
solr_1  | Caused by: org.apache.solr.common.SolrException: Could not load configuration from directory /opt/solr/server/solr/configsets/sunspot
solr_1  | 	at org.apache.solr.core.ConfigSetService$Default.locateInstanceDir(ConfigSetService.java:197) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.ConfigSetService$Default.createCoreResourceLoader(ConfigSetService.java:182) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:75) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.CoreContainer.getConfigSet(CoreContainer.java:1184) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1131) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	... 7 more
solr_1  | 2018-09-21 15:40:39.666 ERROR (coreContainerWorkExecutor-2-thread-1) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be loaded on startup
solr_1  | org.apache.solr.common.SolrException: Unable to create core [test]
solr_1  | 	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1156) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:681) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
db_1    | 2018-09-21 15:39:02.343 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1    | 2018-09-21 15:39:02.343 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1    | 2018-09-21 15:39:02.946 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1    | 2018-09-21 15:39:05.142 UTC [20] LOG:  database system was shut down at 2018-09-18 15:58:13 UTC
db_1    | 2018-09-21 15:39:05.731 UTC [1] LOG:  database system is ready to accept connections
solr_1  | 	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197) ~[metrics-core-3.2.6.jar:3.2.6]
solr_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
solr_1  | 	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:209) ~[solr-solrj-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:14]
solr_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
solr_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
solr_1  | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
solr_1  | Caused by: org.apache.solr.common.SolrException: Could not load configuration from directory /opt/solr/server/solr/configsets/sunspot
solr_1  | 	at org.apache.solr.core.ConfigSetService$Default.locateInstanceDir(ConfigSetService.java:197) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.ConfigSetService$Default.createCoreResourceLoader(ConfigSetService.java:182) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:75) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.CoreContainer.getConfigSet(CoreContainer.java:1184) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1131) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	... 7 more
solr_1  | 2018-09-21 15:40:39.670 ERROR (coreContainerWorkExecutor-2-thread-1) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be loaded on startup
solr_1  | org.apache.solr.common.SolrException: Unable to create core [default]
solr_1  | 	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1156) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:681) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:197) ~[metrics-core-3.2.6.jar:3.2.6]
solr_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
solr_1  | 	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:209) ~[solr-solrj-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:14]
solr_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
solr_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
solr_1  | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
solr_1  | Caused by: org.apache.solr.common.SolrException: Could not load configuration from directory /opt/solr/server/solr/configsets/sunspot
solr_1  | 	at org.apache.solr.core.ConfigSetService$Default.locateInstanceDir(ConfigSetService.java:197) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.ConfigSetService$Default.createCoreResourceLoader(ConfigSetService.java:182) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:75) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.CoreContainer.getConfigSet(CoreContainer.java:1184) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1131) ~[solr-core-7.4.0.jar:7.4.0 9060ac689c270b02143f375de0348b7f626adebc - jpountz - 2018-06-18 16:55:13]
solr_1  | 	... 7 more
solr_1  | 2018-09-21 15:40:39.760 INFO  (main) [   ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@49e5f737{/solr,file:///opt/solr/server/solr-webapp/webapp/,AVAILABLE}{file:///opt/solr/server//solr-webapp/webapp}
solr_1  | 2018-09-21 15:40:39.850 INFO  (main) [   ] o.e.j.s.AbstractConnector Started ServerConnector@66629f63{HTTP/1.1,[http/1.1]}{0.0.0.0:8983}
solr_1  | 2018-09-21 15:40:39.851 INFO  (main) [   ] o.e.j.s.Server Started @7658ms
```

**Comment by shatalov-boris** [comment]
I think the issue probably has been resolved, but for anyone who expiriences this issue:

It's because your docker container is using default Solr `schema.xml`. Sunspot has modified [schema](https://github.com/sunspot/sunspot/blob/master/sunspot_solr/solr/solr/configsets/sunspot/conf/schema.xml) that you need to use. That's why you got `undefined field type` error.
So you should tell docker to use Sunspot schema. 
I did it like this:
`docker-compose.yml` solr part:
```
  solr:
    build:
      context: .
      dockerfile: Dockerfile-solr
    volumes:
      - solr_data:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - development
```

`Dockerfile-solr`:
```
FROM solr:7.4.0

COPY ./config/solr/schema.xml /opt/solr/server/solr/configsets/_default/conf/schema.xml
```

So I keep  `schema.xml` in my local folder and copy it to default solr configset. This way it automatically creates new cores with this schema.

Also you can keep your current config and just copy new `schema.xml` to docker container. Then you simply need to restart your container.

**Comment by mlh758** [comment]
This appears to have a good answer, mind if I close this?

**Comment by jabawack81** [comment]
close away, thank you
