### ISSUE TITLE
Issue with JSON arrays format on latest rsolr + sunspot

### ISSUE THREAD

**Issue by serggl** [sunspot/sunspot#948]
```
RSolr::Error::Http - 400 Bad Request
Error: {"responseHeader":{"status":400,"QTime":0},"error":{"metadata":["error-class","org.apache.solr.common.SolrException","root-error-class","org.apache.solr.common.SolrException"],"msg":"Error parsing JSON field value. Unexpected OBJECT_START at [787], field=installation_tags_sms","code":400}}

URI: http://solr-host/solr/production/update?wt=json&commitWithin=1500
Request Headers: {"Content-Type"=>"application/json"}
Request Data: "[{\"id\":\"some ID\",___truncated___,\"installation_tags_sms\":[{\"set\":\"value 1\"},{\"set\":\"value 2\"}]]"

Backtrace: /usr/local/bundle/gems/rsolr-2.2.1/lib/rsolr/client.rb:206:in `rescue in execute'
/usr/local/bundle/gems/rsolr-2.2.1/lib/rsolr/client.rb:196:in `execute'
/app/config/initializers/sunspot.rb:64:in `block in execute'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/core_ext/benchmark.rb:14:in `ms'
/app/config/initializers/sunspot.rb:63:in `execute'
```

Seem like some sort of regression of https://github.com/rsolr/rsolr/issues/193 but ot sure, needs to be verified whenever the issue is on sunspot side or not

**Comment by serggl** [comment]
UPD: That relates to atomic updates only

**Comment by serggl** [comment]
submitted a ticket to rsolr team https://github.com/rsolr/rsolr/issues/200
